// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: sku-limiter.proto

package skulimiter

import (
	"context"

	desc "git.ozon.dev/dlukashov/sku-limiter/pkg/sku-limiter"
)

// AddOrder сохраняем заказ в redis
func (i *Implementation) AddOrder(ctx context.Context, req *desc.AORequest) (*desc.AOResponse, error) {
	err := i.addOrderRs(ctx, req.UserId, req.OrderId, req.OrderTs, req.Content)
	return &desc.AOResponse{Status: "OK"}, err
}
