// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: sku-limiter.proto

package skulimiter

import (
	"context"

	desc "git.ozon.dev/dlukashov/sku-limiter/pkg/sku-limiter"
)

// DelLimitSKU удалим список SKU и их лимиты
func (i *Implementation) DelLimitSKU(ctx context.Context, req *desc.DLRequest) (*desc.DLResponse, error) {
	err := i.delLimitSKURs(ctx, &req.Skus, &req.Actions)
	return &desc.DLResponse{Status: "OK"}, err
}
