// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: sku-limiter.proto

package skulimiter

import (
	"context"

	desc "git.ozon.dev/dlukashov/sku-limiter/pkg/sku-limiter"
)

// DelLimitUser почистить (ресетнуть) остатки по всем лимитам для списка юзеров и опционально акциям
func (i *Implementation) DelLimitUser(ctx context.Context, req *desc.DLURequest) (*desc.DLUResponse, error) {
	err := i.delLimitUserRs(ctx, &req.Users, &req.Actions)
	return &desc.DLUResponse{Status: "OK"}, err
}
