// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: sku-limiter.proto

package skulimiter

import (
	"context"

	desc "git.ozon.dev/dlukashov/sku-limiter/pkg/sku-limiter"
)

// GetLimitSKU получить акции (лимиты) по списку СКУ + фильтр по акциям
func (i *Implementation) GetLimitSKU(ctx context.Context, req *desc.GLRequest) (*desc.GLResponse, error) {
	actionsAllSKU, err := i.getLimitSKUnitsRs(ctx, req.Skus, req.Actions)
	return &desc.GLResponse{Skus: *actionsAllSKU}, err
}
