// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: sku-limiter.proto

package skulimiter

import (
	"context"

	desc "git.ozon.dev/dlukashov/sku-limiter/pkg/sku-limiter"
)

// GetLimitUsersActions получить остатки по всем лимитам для списка юзеров и опционально акциям
func (i *Implementation) GetLimitUsersActions(ctx context.Context, req *desc.GLUARequest) (*desc.GLUAResponse, error) {
	usersActions, err := i.getLimitsUsersActionsRs(ctx, &req.Users, &req.Actions)
	return &desc.GLUAResponse{Users: *usersActions}, err
}
