// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: sku-limiter.proto

package skulimiter

import (
	"context"

	desc "git.ozon.dev/dlukashov/sku-limiter/pkg/sku-limiter"
)

// GetLimitUserSKUs получить остатки по лимитам для 1 юзера по заданному списку sku
func (i *Implementation) GetLimitUserSKUs(ctx context.Context, req *desc.GLUSRequest) (*desc.GLUSResponse, error) {
	UserlimitsSKUnits, err := i.getUserLimitsSKUnitsRs(ctx, &req.Skus, req.UserId)
	return &desc.GLUSResponse{UserId: req.UserId, Sku: *UserlimitsSKUnits}, err
}
