// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: sku-limiter.proto

package skulimiter

import (
	desc "git.ozon.dev/dlukashov/sku-limiter/pkg/sku-limiter"
	"github.com/go-redis/redis/v7"
	"github.com/utrack/clay/v2/transport"
)

type Implementation struct {
	db *redis.Client
}

// NewSKULimiter create new Implementation
func NewSKULimiter() *Implementation {
	return &Implementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewSKULimiterServiceDesc(i)
}

// SetDB установить БД
func (i *Implementation) SetDB(db *redis.Client) {
	i.db = db
}

// GetDB вернуть БД
func (i *Implementation) GetDB() *redis.Client {
	return i.db
}
